---
# Guide: https://github.com/eclipse-cdt/cdt/blob/main/Downloads.md
# from: https://www.eclipse.org/downloads/packages/release

- name: installed exists
  stat:
    path: "{{ install_dir }}/eclipse.ini"
  register: install

- name: launcher exists
  stat:
    path: "{{ desktop_file_dir }}/{{ desktop_file }}"
  register: launcher

- name: Install
  block:
  - name: Create install directory
    become: yes
    ansible.builtin.file:
      path: "{{ download_dir }}"
      state: directory
      owner: "{{ ansible_env.USER }}"

  - name: Download CDT
    ansible.builtin.get_url:
      url: "{{ download_url }}"
      dest: "{{ download_dir }}/{{ file_name }}"

  - name: Unarchive
    ansible.builtin.unarchive:
      src: "{{ download_dir }}/{{ file_name }}"
      dest: "{{ download_dir }}/"
      creates: "{{ install_dir }}/"
      remote_src: yes

  when: not install.stat.exists

- name: Launcher
  become: true
  ansible.builtin.template:
    src: eclipse.desktop.j2
    dest: "{{ desktop_file_dir }}/{{ desktop_file }}"
    owner: root
    group: root
  when: not launcher.stat.exists