- name: Setting filesystem Prefix when rpm-ostree
  ansible.builtin.set_fact:
    download_dir: "/var{{ download_dir }}"
    desktop_file_path: "/var{{ desktop_file_path }}"

- name: include source
  include_tasks: "from:/{{ source }}/main.yml"