- hosts: localhost #, node
  vars:
    foo: "bar"
  vars_files:
    - vars/Env.yml
    - vars/debug.yml
  roles:
  # - bugfix/java-17  # Run this before Eclipse install
  - Eclipse CDT
  - compiler
  - builder
